---

- name: Network appliance configuration
  hosts: spine-*,rack-1-leaf*, rack-2-leaf*
  become: true

  handlers:
    - name: Import re-usable handlers
      ansible.builtin.import_tasks: "handlers/main.yaml"

  tasks:
    - name: Configure interfaces
      ansible.builtin.template:
        src: "{{ interfaces_conf_file }}"
        dest: /etc/network/interfaces
        validate: ifup -a -s -i %s
        mode: "0644"
      notify: Apply interface changes

    - name: Configure FRR daemons file
      ansible.builtin.template:
        src: "{{ frr_daemons_file }}"
        dest: /etc/frr/daemons
        mode: "0640"
      notify:
        - Restart frr

    - name: Configure FRR
      ansible.builtin.template:
        src: "{{ frr_conf_file }}"
        dest: /etc/frr/frr.conf
        validate: vtysh -f %s --dryrun
        mode: "0640"
      notify:
        - Reload frr

- name: Configure Servers
  hosts: rack-1-host*
  gather_facts: true
  become: true

  vars_files:
    - group_vars/linux-hosts.yaml

  handlers:
    - name: Import re-usable handlers
      ansible.builtin.import_tasks: "handlers/main.yaml"

  tasks:
    - name: Build list of YUM repo files
      ansible.builtin.find:
        paths:
          - /etc/yum.repos.d/
        patterns:
          - 'CentOS-*'
        use_regex: false
      register: yum_repo_files
      when: ansible_distribution == "CentOS"

    - name: Comment out YUM mirrorlist links
      ansible.builtin.replace:
        dest: "{{ item.path }}"
        regexp: '^mirrorlist'
        replace: '#mirrorlist'
        backup: true
      loop: "{{ yum_repo_files.files }}"
      when: ansible_distribution == "CentOS"

    - name: Replace YUM baseurl
      ansible.builtin.replace:
        dest: "{{ item.path }}"
        regexp: '^#baseurl=http://mirror.centos.org'
        replace: 'baseurl=http://vault.centos.org'
      loop: "{{ yum_repo_files.files }}"
      when: ansible_distribution == "CentOS"

    - name: Ensure ipv6 is enabled
      ansible.posix.sysctl:
        name: net.ipv6.conf.all.disable_ipv6
        value: '0'
        sysctl_file: /etc/sysctl.conf
        state: present
        reload: true

    - name: Ensure zebra and bgpd daemons are enabled
      tags:
        - never
        - frr
      ansible.builtin.lineinfile:
        path: /etc/frr/daemons
        regexp: '(^zebra|bgpd=)no'
        backrefs: true
        line: '\g<1>yes'
        state: present

# Is this still required?  It's not included in the daemons file
# included in the ovn-bgp-agent repo that stack.sh clones
# zebra_options=("-A 127.0.0.1 --vrfwnetns")
    # - name: Ensure VRFWNETNS is enabled at the zebra options
      # tags:
      #   - never
      #   - frr
    #   ansible.builtin.lineinfile:
    #     path: /etc/frr/daemons
    #     regexp: '--vrfwnetns'
    #     state: absent
    #   check_mode: true
    #   changed_when: false
    #   register: vrfwnetns_found

    # - name: Add missing VRFWNETNS to zebra options
      # tags:
      #   - never
      #   - frr
    #   ansible.builtin.lineinfile:
    #     path: /etc/frr/daemons
    #     regexp: 'zebra_options=(.*)(\")'
    #     backrefs: true
    #     line: 'zebra_options=\g<1> --vrfwnetns\g<2>'
    #     state: present
    #   when: not vrfwnetns_found.found

    - name: Configure FRR
      tags:
        - never
        - frr
      ansible.builtin.template:
        src: "{{ frr_conf_file }}"
        dest: /etc/frr/frr.conf
        validate: vtysh -f %s --dryrun
        mode: "0640"
      notify:
        - Reload frr

    - name: Start frr now and on boot
      tags:
        - never
        - frr
    # FCN of module does not work; get module not found error
      systemd:
        state: started
        enabled: true
        name: frr

    - name: Centos - Configure dummy interface IP
      community.general.nmcli:
        type: dummy
        conn_name: '{{ item.conn_name }}'
        ip4: '{{ item.ip4 }}'
        state: present
      with_items:
        - '{{ nmcli_dummy }}'
      when: ansible_distribution == "CentOS"

    - name: Centos - Configure Ethernet interface IPs
      community.general.nmcli:
        type: ethernet
        conn_name: '{{ item.conn_name }}'
        ip4: '{{ item.ip4 }}'
        state: present
      with_items:
        - '{{ nmcli_ethernet }}'
      when: ansible_distribution == "CentOS"

    - name: Centos - Bring up eth1 and eth2
      ansible.builtin.command:
        cmd: "nmcli con up {{ item }}"
      register: int_up_result
      changed_when: 'int_up_result.rc == 0 and "File exists" not in int_up_result.stderr'
      loop:
        - eth1
        - eth2
      when: ansible_distribution == "CentOS"

    - name: Ubuntu - add netplan config for lo, eth1, and eth2
      ansible.builtin.template:
        src: ubuntu-netplan.j2
        dest: /etc/netplan/02-netcfg.yaml
        mode: '0600'
      when: ansible_distribution == "Ubuntu"

    - name: Ubuntu - Apply netplan configuration
      ansible.builtin.command: netplan apply
      when: ansible_distribution == "Ubuntu"

    - name: Apply iptables SNAT rule for r-1-h-1 loopback to r-1-h-2
      tags: andy
      ansible.builtin.iptables:
        table: nat
        chain: POSTROUTING
        out_interface: eth1
        destination: "{{ hostvars['rack-1-host-2']['dummy0_ipv4'] | ansible.utils.ipaddr('network') }}"
        protocol: all
        jump: SNAT
        to_source: "{{ dummy0_ipv4 | ansible.utils.ipaddr('network') }}"
      when: inventory_hostname == 'rack-1-host-1'

    - name: Create dir for devstack installation
      ansible.builtin.file:
        owner: vagrant
        group: root
        path: /opt/stack
        mode: '0755'
        state: directory

    - name: Clone ovn-bgp-agent repo
      ansible.builtin.git:
        clone: true
        force: true
        repo: https://opendev.org/openstack/ovn-bgp-agent
        dest: /opt/stack/ovn-bgp-agent
        version: stable/2023.2

    - name: Clone devstack repo
      ansible.builtin.git:
        clone: true
        repo: https://opendev.org/openstack/devstack
        dest: /opt/stack/devstack
        version: stable/2023.2

    - name: Fix ownership of ovn-bgp-agent
      ansible.builtin.file:
        dest: /opt/stack/ovn-bgp-agent
        owner: vagrant
        group: root
        recurse: true

    - name: Fix ownership of devstack
      ansible.builtin.file:
        dest: /opt/stack/devstack
        owner: vagrant
        group: root
        recurse: true

    - name: Disable tls-proxy requirement for ovn-bgp-agent
      ansible.builtin.lineinfile:
        line: '         echo_summary "Info: tls-proxy is not enabled"'
        search_string: 'die $LINENO "OVN BGP Agent requires TLS to be enabled'
        path: /opt/stack/ovn-bgp-agent/devstack/lib/ovn-bgp-agent
      when: not ansible_check_mode

    - name: Add devstack local.conf file to controller node
      ansible.builtin.template:
        src: devstack-controller-local.conf.j2
        dest: /opt/stack/devstack/local.conf
        mode: '0644'
        owner: vagrant
        group: root
      when: inventory_hostname == "rack-1-host-1"

    - name: Add devstack local.conf file to compute node
      ansible.builtin.template:
        src: devstack-compute-local.conf.j2
        dest: /opt/stack/devstack/local.conf
        mode: '0644'
        owner: vagrant
        group: root
      when:
        - inventory_hostname != "rack-1-host-1"
        - inventory_hostname is match("rack-\d-host-\d")

    # Each compute node needs connectivity to the controller node before devstack will install properly
    # As devstack is also installing frr we can't use BGP to distribute these routes to start, but
    # it can be relied upon post-frr install
    - name: Configure static routes on rack-1-host-2 for host-1 loopback
      ansible.builtin.command:
        cmd: "ip route add 99.99.1.1/32 via 100.65.1.5"
      register: ip_route_result
      changed_when: 'ip_route_result.rc == 0 and "File exists" not in ip_route_result.stderr'
      failed_when: 'ip_route_result.rc != 0 and "File exists" not in ip_route_result.stderr'
      when: inventory_hostname == 'rack-1-host-2'

    - name: Configure static routes on rack-1-host-2 for host-1 p2p eth1 addr
      ansible.builtin.command:
        cmd: "ip route add 100.65.1.2/32 via 100.65.1.5"
      register: ip_route_result
      changed_when: 'ip_route_result.rc == 0 and "File exists" not in ip_route_result.stderr'
      failed_when: 'ip_route_result.rc != 0 and "File exists" not in ip_route_result.stderr'
      when: inventory_hostname == 'rack-1-host-2'
