---

# A simple no-op playbook to allow vagrant to call the ansible provisioner
# and create the inventory file for us
- name: No-op playbook
  hosts: all
  gather_facts: false
  tasks:
    - name: Hello World
      ansible.builtin.debug:
        msg: "Hello World"
