---

frr_daemons_file: "config-files/shared/etc/frr/daemons"
etc_hosts_file: "config-files/{{ inventory_hostname }}/etc/hosts"
etc_hostname_file: "config-files/{{ inventory_hostname }}/etc/hostname"
etc_resolv_conf_file: "config-files/{{ inventory_hostname }}/etc/resolv.conf"
cumulus_dirs: "config-files/shared/cumulus/"
